config/routes.rb
Rails.application.routes.draw do

	resources :sessions, only: [:new, :create, :destroy]
	resources :users, only: [:new, :create]
	resources :lists do
	resources :todos
	end

end

app/models/list.rb
class List < ActiveRecord::Base
	validates :name, presence: true
	belongs_to :user
	has_many :todos
end

app/models/todo.rb
class Todo < ActiveRecord::Base

	belongs_to :list
	belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
	has_secure_password
	has_many :lists
	has_many :todos, through: :lists
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  helper_method :current_user

  def ensure_logged_in
    unless current_user
      flash[:alert] = "Please log in"
      redirect_to new_session_path
    end
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController

before_filter :ensure_logged_in, only: [:index, :show, :create, :destroy]

  def index
  	@lists = current_user.lists.order(created_at: :desc)
  end

  def new
  	@list = List.new
  end

  def show
  	@list = List.find(params[:id])
    @todos = @list.todos.order(created_at: :desc)
  end

  def create
  	@list = List.new(list_params)
    @list.user_id = current_user.id
  	if @list.save
  		redirect_to :back 
  	else
  		render :new
  	end
  end

  def update
  	@list = List.find(params[:id])

  	if @list.update_attributes(list_params)
  		redirect_to list_path(@list)
  	else
  		render :edit
  	end
  end

  def destroy
  	@list = List.find(params[:id])
  	@list.destroy
  	redirect_to lists_path
  end

  private
  def list_params
  	params.require(:list).permit(:name, :user_id)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to lists_url, notice: "Logged in!"
    else
		flash.now[:alert] = "Invalid email or password"
		render "new"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to lists_url, notice: "Logged out!"
  end
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
	before_filter :load_list
	before_filter :ensure_logged_in, only: [:index, :show, :create, :destroy]

  def index
    @todos = current_user.todos.order(created_at: :desc)
  end

  # def show
  # 	@todo = Todo.find(params[:id])
  # end

  def create
  	@todo = @list.todos.build(todo_params)
  	@todo.user = current_user

  	if @todo.save
  		redirect_to :back 
  	else
  		render 'lists/show'
  	end
  end

  def destroy
  	@todo = Todo.find(params[:id])
  	@todo.destroy
  end

  private
  def todo_params
  	params.require(:todo).permit(:task, :list_id, :user_id)
  end

  def load_list
  	@list = List.find(params[:list_id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to lists_url, notice: "Signed up!"
    else
      render "new"
    end
  end

  private
  def user_params
    params.require(:user).permit(:firstName, :lastName, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/list_helper.rb
module ListHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- load MUI -->
<link href="//cdn.muicss.com/mui-0.1.13/css/mui.css" rel="stylesheet" type="text/css" />
<script src="//cdn.muicss.com/mui-0.1.13/js/mui.min.js"></script>

  </head>

 <body>
  <div class="mui-appbar">
    <table width="100%">
    <tr style="vertical-align:middle;">
      <td class="mui-appbar-height">Left Side</td>
      <td class="mui-appbar-height" align="right">    
      <p class="userinfo">
      <% if current_user %>
        Signed in as <%= current_user.email %> <%= link_to "Log out", session_path("current"), :method => :delete %>
      <% else %>
        <%= link_to "Log in", new_session_path %> or <%= link_to "Sign up", new_user_path %>
      <% end %>
    </p></td>
    </tr>
    </table>
  </div>
    <% if flash[:notice] %>
      <p id="notice"><%= flash[:notice] %></p>
    <% end %>
    <% if flash[:alert] %>
      <p id="alert"><%= flash[:alert] %></p>
    <% end %>

  <%= yield %>

  </body>
    <div class="mui-container">
      <div class="mui-panel">
        <h1>My Title</h1>
        <button class="mui-btn mui-btn-primary mui-btn-raised">My Button</button>
      </div>
    </div>
  </body>
</html>

app/views/lists/_form.html.erb
<%= form_for List.new do |f| %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/lists/edit.html.erb
<h1>Lists#edit</h1>
<p>Find me in app/views/lists/edit.html.erb</p>

app/views/lists/index.html.erb
 <%= render 'lists/form' %>
 <div class="mui-container">
 	<div class="mui-panel">
  <!-- content -->

<% @lists.each do |list| %>

	<p><%= link_to list.name, "/lists/#{list.id}" %></p>

<% end %>

</div>
</div>

app/views/lists/new.html.erb
<h1>New List</h1>

<%= render 'form' %>

<%= link_to 'Back', lists_path %>

app/views/lists/show.html.erb
  <p>Todos for <%= @list.name %></p>
<div class="mui-container">
  <div class="mui-panel">
  <% @list.todos.each do |todo| %>
    <p>
      <%= todo.task %>
      <br>
      <% if todo.user != nil %>
        <em> by <%= todo.user.email %></em>
        Added on: <%= todo.created_at %>
      <% end %>
    </p>
  <% end %>
  </div>
</div>
  <% if current_user %>
  <h4>New Review</h4>

    <div class="mui-container">
      <div class="mui-panel">

  <%= form_for([@list, Todo.new]) do |f| %>

    <div class="field">
      <%= f.label :task %><br />
      <%= f.text_area :task %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
  <% end %>

  </div>
  </div>

<% else %>
  <p>Please <%= link_to "log in", new_session_path %> to add a task.</p> 
<% end %>

app/views/todos/edit.html.erb
<h1>Todos#edit</h1>
<p>Find me in app/views/todos/edit.html.erb</p>

app/views/todos/index.html.erb
<h1>Todos#index</h1>
<p>Find me in app/views/todos/index.html.erb</p>

app/views/todos/new.html.erb
<h1>Todos#new</h1>
<p>Find me in app/views/todos/new.html.erb</p>

app/views/todos/show.html.erb
<h1>Todos#show</h1>
<p>Find me in app/views/todos/show.html.erb</p>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% for message in @user.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :firstName %><br/>
    <%= f.text_field :firstName %>
  </div>
  <div class="field">
    <%= f.label :lastName %><br/>
    <%= f.text_field :lastName %>
  </div>
  <div class="field">
    <%= f.label :email %><br/>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br/>
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br/>
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions"><%= f.submit %></div>
<% end %>